### ISSUE TITLE
Connection lost

### ISSUE THREAD

**Issue by erwrow** [256dpi/processing-mqtt#14] opened 2017-12-07 14:50 UTC
Hi, ¿how can i know when i've lost the connection?

**Comment by 256dpi** [comment] 2017-12-08 08:36
Unfortunately, this is not supported at the moment and I don't have much time to implement it.... Sorry.

**Comment by 256dpi** [comment] 2017-12-27 11:37
Duplicate of #6.

**Comment by erwrow** [comment] 2017-12-28 12:37
Sorry for insisting, but it's not a duplicate. When i loss connection, or i can't connect your librarie throws an exception over the console with something like this: [MQTT] failed to subscribe:... and then say that the client isn't connected, i want to pass that output to the screen so the user knows what's happening

**Comment by 256dpi** [comment] 2017-12-28 13:18
I see, I'll think about a fix for that.

**Comment by cimba007** [comment] 2018-03-30 18:09
Any progress on this issue?

**Comment by 256dpi** [comment] 2018-12-11 14:28
Done in `v1.7.0`.

**Closed as completed by 256dpi** 2018-12-11 14:28 UTC
