### ISSUE TITLE
Receive Messages in Python Mode

### ISSUE THREAD

**Issue by simonrieser** [256dpi/processing-mqtt#19] opened 2018-07-30 18:56 UTC
I always get the message "messageReceived callback not found!". How do I need to call "client = MQTTClient(this)" to register the callback function correctly?

Thank you for your help!

**Comment by TLatour** [comment] 2018-08-03 12:13
This comment may help solving the problem I hope. 
I have the same problem and could'nt find any solution so far.
The example works perfectly with the Java mode example, but gives the error message in Python mode. My translation of the Java example code in Python (Java left as comment for comparison) is here under:

```#import mqtt.*;
add_library('mqtt')

#MQTTClient client;

#void setup() {
#  client = new MQTTClient(this);
#  client.connect("mqtt://try:try@broker.shiftr.io", "processing");
#  client.subscribe("/example");
#  // client.unsubscribe("/example");
#}

global client
client=MQTTClient(this)

def setup():
    size(50,50)
    client.connect("mqtt://try:try@broker.shiftr.io", "processing")
    client.subscribe("/example")

#void draw() {}
def draw():
    pass

#void keyPressed() {
#  client.publish("/hello", "world");
#}
def keyPressed():
    client.publish("/hello","world")
    
#void messageReceived(String topic, byte[] payload) {
#  println("new message: " + topic + " - " + new String(payload));
#}
def messageReceived(topic,payload):
    print "new message: " + topic + " - " + str(payload)
```

This other test code works perfectly well in Java with Node-Red (and its MQTT broker on my local machine, connected to another python application using paho.mqtt.python that sends MQTT messages), but not in Python. I am a basic Python programmer, may be something is wrong in the messageReceived function definition.

```import mqtt.*;

MQTTClient client;

void setup() {
  client = new MQTTClient(this);
  client.connect("mqtt://localhost", "Traces");
  client.subscribe("/Traces/MapBox");
}

void draw() {}

void keyPressed() {
  client.publish("/Traces/Processing", "Key Pressed: " + key);
}

void messageReceived(String topic, byte[] payload) {
  println("new message: " + topic + " - " + new String(payload));
}
```

```add_library('mqtt')

global client
client=MQTTClient(this)

def setup():
    brokerAddress="mqtt://127.0.0.1"
    client.connect(brokerAddress,"Traces")
    client.subscribe("/Traces/MapBox")

def draw():
    pass

def keyPressed():
    client.publish("/Traces/Processing", "Key Pressed: " + key)
    
def messageReceived(topic,payload):
    print 'topic:',topic
    print 'payload:',payload
```

**Comment by 256dpi** [comment] 2019-02-25 08:54
I just released a new version that ships with an alternative method to receive the events:
https://github.com/256dpi/processing-mqtt/blob/master/examples/PublishSubscribeListener/PublishSubscribeListener.pde.

This might work also in Python mode.

**Comment by 256dpi** [comment] 2019-02-25 08:55
Closing as duplicate of #21

**Closed as completed by 256dpi** 2019-02-25 08:54 UTC
